// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/rizkix/wired/config"
	"github.com/rizkix/wired/controller"
	"github.com/rizkix/wired/delivery/grpc"
	"github.com/rizkix/wired/delivery/http"
	"github.com/rizkix/wired/plugin"
	"github.com/rizkix/wired/repo"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	configConfig := config.New()
	db, err := plugin.NewMysqlConnection()
	if err != nil {
		return App{}, err
	}
	repoRepo, err := repo.New(configConfig, db)
	if err != nil {
		return App{}, err
	}
	controllerController := controller.New(configConfig, repoRepo)
	handler := http.New(controllerController)
	grpcHandler := grpc.New(controllerController)
	app := NewApp(configConfig, handler, grpcHandler)
	return app, nil
}
